[changelog]
header = "# 📦 Changelog\n\n"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message }} ({{ commit.id | truncate(length=7) }})
{% endfor %}
{% endfor %}
"""
footer = ""

[git]
conventional_commits = true
filter_commits = true
tag_pattern = "v[0-9]*"