// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCqWAQoKUGxheWVyVHlwZRIUChBQTEFZ",
            "RVJfVFlQRV9OT05FEAASFgoSUExBWUVSX1RZUEVfS05JR0hUEAESFAoQUExB",
            "WUVSX1RZUEVfTUFHRRACEhYKElBMQVlFUl9UWVBFX0FSQ0hFUhADEhUKEVBM",
            "QVlFUl9UWVBFX0RVTU1ZEAQSFQoRUExBWUVSX1RZUEVfSFVNQU4QBSqDAQoL",
            "TG9naW5SZXN1bHQSEQoNTE9HSU5fU1VDQ0VTUxAAEhkKFUxPR0lOX0VNQUlM",
            "X05PVF9GT1VORBACEhUKEUxPR0lOX1BXX01JU01BVENIEAMSFgoSTE9HSU5f",
            "U0VSVkVSX0VSUk9SEGISFwoTTE9HSU5fREVGQVVMVF9FUlJPUhBjKnsKDlJl",
            "Z2lzdGVyUmVzdWx0EhQKEFJFR0lTVEVSX1NVQ0NFU1MQABIcChhSRUdJU1RF",
            "Ul9EVVBMSUNBVEVfRU1BSUwQARIZChVSRUdJU1RFUl9TRVJWRVJfRVJST1IQ",
            "YhIaChZSRUdJU1RFUl9ERUZBVUxUX0VSUk9SEGNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.PlayerType), typeof(global::Protocol.LoginResult), typeof(global::Protocol.RegisterResult), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum PlayerType {
    [pbr::OriginalName("PLAYER_TYPE_NONE")] None = 0,
    [pbr::OriginalName("PLAYER_TYPE_KNIGHT")] Knight = 1,
    [pbr::OriginalName("PLAYER_TYPE_MAGE")] Mage = 2,
    [pbr::OriginalName("PLAYER_TYPE_ARCHER")] Archer = 3,
    [pbr::OriginalName("PLAYER_TYPE_DUMMY")] Dummy = 4,
    [pbr::OriginalName("PLAYER_TYPE_HUMAN")] Human = 5,
  }

  public enum LoginResult {
    [pbr::OriginalName("LOGIN_SUCCESS")] LoginSuccess = 0,
    /// <summary>
    /// Email 미등록
    /// </summary>
    [pbr::OriginalName("LOGIN_EMAIL_NOT_FOUND")] LoginEmailNotFound = 2,
    /// <summary>
    /// 비밀번호 불일치
    /// </summary>
    [pbr::OriginalName("LOGIN_PW_MISMATCH")] LoginPwMismatch = 3,
    /// <summary>
    /// 기타 내부 오류
    /// </summary>
    [pbr::OriginalName("LOGIN_SERVER_ERROR")] LoginServerError = 98,
    /// <summary>
    /// 기본 에러
    /// </summary>
    [pbr::OriginalName("LOGIN_DEFAULT_ERROR")] LoginDefaultError = 99,
  }

  public enum RegisterResult {
    [pbr::OriginalName("REGISTER_SUCCESS")] RegisterSuccess = 0,
    /// <summary>
    /// 이메일 중복
    /// </summary>
    [pbr::OriginalName("REGISTER_DUPLICATE_EMAIL")] RegisterDuplicateEmail = 1,
    /// <summary>
    /// 기타 내부 오류
    /// </summary>
    [pbr::OriginalName("REGISTER_SERVER_ERROR")] RegisterServerError = 98,
    /// <summary>
    /// 기본 에러
    /// </summary>
    [pbr::OriginalName("REGISTER_DEFAULT_ERROR")] RegisterDefaultError = 99,
  }

  #endregion

}

#endregion Designer generated code
