name: Release and Changelog

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Get latest tag
      id: get_tag
      run: |
        TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "latest_tag=$TAG" >> $GITHUB_OUTPUT

    - name: Bump patch version (v0.0.X)
      id: bump
      run: |
        old="${{ steps.get_tag.outputs.latest_tag }}"
        ver=$(echo $old | sed -E 's/v([0-9]+)\.([0-9]+)\.([0-9]+)/\1.\2.\3/')
        IFS='.' read -ra PARTS <<< "$ver"
        PATCH=$((PARTS[2]+1))
        NEW_TAG="v${PARTS[0]}.${PARTS[1]}.$PATCH"
        echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

    - name: Create new tag
      run: |
        git tag ${{ steps.bump.outputs.new_tag }}
        git push origin ${{ steps.bump.outputs.new_tag }}

    - name: Install git-cliff
      uses: taiki-e/install-action@v2
      with:
        tool: git-cliff

    - name: Generate changelog
      run: git-cliff -o CHANGELOG.md

    - name: Commit & Push Changelog
      run: |
        git add CHANGELOG.md
        git commit -m "update changelog for ${{ steps.bump.outputs.new_tag }} [skip ci]" || echo "No changes"
        git push